version: '3.9'
services:
  postgres:
    image: postgres:17
    container_name: db-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass2word
      POSTGRES_DB: postgres
    volumes:
      - ./postgres/postgres-data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s      
      retries: 10  
      start_period: 30s 
  
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.4
    container_name: keycloak
    command: start-dev --import-realm --features=scripts --spi-script-upload-enabled=true
    ports:
      - "8080:8080"
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_PORT: 5432
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: pass2word
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_FEATURES: account3,admin-fine-grained-authz,scripts
      KC_SPI_SCRIPT_UPLOAD_ENABLED: true
    volumes:
      - ./Keycloak/themes:/opt/keycloak/themes
      - ./Keycloak/keycloak-conf:/opt/keycloak/conf
      - ./Keycloak/realm-export:/opt/keycloak/data/import
      - ./Keycloak/realm-export:/tmp/realm-export
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  go-wongnok:
    build:
      context: ./GO-wongnok
      dockerfile: Dockerfile
    container_name: go-wongnok
    ports:
      - "8082:8080"
    environment:
      - DATABASE_URL=postgres://postgres:pass2word@postgres:5432/wongnok
      - GOOSE_DRIVER=postgres
      - GOOSE_DBSTRING=postgres://postgres:pass2word@postgres:5432/wongnok
      - GOOSE_MIGRATION_DIR=./migrations
      - KEYCLOAK_CLIENT_ID=wongnok
      - KEYCLOAK_CLIENT_SECRET=zDFCurmEkhGN1iIxA3NhmpVlft2qCncJ
      - KEYCLOAK_REDIRECT_URL=http://localhost/api/v1/callback
      - KEYCLOAK_REALM=Devpool_project
      - KEYCLOAK_URL=http://keycloak:8080
    extra_hosts:
      - "localhost:host-gateway"      
    # volumes:
    #     - ./GO-wongnok:/app
    depends_on:
      postgres:
        condition: service_healthy
      keycloak:
        condition: service_started
    restart: unless-stopped

  wongnok-web:
    build:
      context: ./wongnok-web
      dockerfile: Dockerfile
    container_name: wongnok-web
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_BASE_PATH=http://localhost
      - INTERNAL_API_BASE=http://go-wongnok:8080
      - KEYCLOAK_CLIENT_ID=wongnok
      - KEYCLOAK_CLIENT_SECRET=zDFCurmEkhGN1iIxA3NhmpVlft2qCncJ
      - KEYCLOAK_ISSUER=http://localhost:8080/realms/Devpool_project
      - KEYCLOAK_POST_LOGOUT_REDIRECT_URI=http://localhost
      - NEXT_PUBLIC_KEYCLOAK_CLIENT_ID=wongnok
      - NEXTAUTH_SECRET=dsafqr234af
      - NEXTAUTH_URL=http://localhost:3000
    volumes:
      - ./wongnok-web:/app
      - /app/node_modules
    depends_on:
      - go-wongnok
    restart: unless-stopped
    extra_hosts:
      - "localhost:host-gateway"
      # - "host.docker.internal:host-gateway"
 
  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx-conf:/etc/nginx/conf.d
      - ./nginx/nginx-html:/usr/share/nginx/html
      - ./nginx/nginx-logs:/var/log/nginx
      - ./nginx/ssl-certs:/etc/ssl/certs
    depends_on:
      - keycloak
      - go-wongnok
      - wongnok-web
    restart: unless-stopped