// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package favorite_test

import (
	"wongnok/internal/model"
	"wongnok/internal/model/dto"

	"github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// NewMockIHandler creates a new instance of MockIHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIHandler {
	mock := &MockIHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIHandler is an autogenerated mock type for the IHandler type
type MockIHandler struct {
	mock.Mock
}

type MockIHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIHandler) EXPECT() *MockIHandler_Expecter {
	return &MockIHandler_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockIHandler
func (_mock *MockIHandler) Create(ctx *gin.Context) {
	_mock.Called(ctx)
	return
}

// MockIHandler_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockIHandler_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx *gin.Context
func (_e *MockIHandler_Expecter) Create(ctx interface{}) *MockIHandler_Create_Call {
	return &MockIHandler_Create_Call{Call: _e.mock.On("Create", ctx)}
}

func (_c *MockIHandler_Create_Call) Run(run func(ctx *gin.Context)) *MockIHandler_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gin.Context
		if args[0] != nil {
			arg0 = args[0].(*gin.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIHandler_Create_Call) Return() *MockIHandler_Create_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockIHandler_Create_Call) RunAndReturn(run func(ctx *gin.Context)) *MockIHandler_Create_Call {
	_c.Run(run)
	return _c
}

// Get provides a mock function for the type MockIHandler
func (_mock *MockIHandler) Get(ctx *gin.Context) {
	_mock.Called(ctx)
	return
}

// MockIHandler_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockIHandler_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx *gin.Context
func (_e *MockIHandler_Expecter) Get(ctx interface{}) *MockIHandler_Get_Call {
	return &MockIHandler_Get_Call{Call: _e.mock.On("Get", ctx)}
}

func (_c *MockIHandler_Get_Call) Run(run func(ctx *gin.Context)) *MockIHandler_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gin.Context
		if args[0] != nil {
			arg0 = args[0].(*gin.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIHandler_Get_Call) Return() *MockIHandler_Get_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockIHandler_Get_Call) RunAndReturn(run func(ctx *gin.Context)) *MockIHandler_Get_Call {
	_c.Run(run)
	return _c
}

// GetByUser provides a mock function for the type MockIHandler
func (_mock *MockIHandler) GetByUser(ctx *gin.Context) {
	_mock.Called(ctx)
	return
}

// MockIHandler_GetByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUser'
type MockIHandler_GetByUser_Call struct {
	*mock.Call
}

// GetByUser is a helper method to define mock.On call
//   - ctx *gin.Context
func (_e *MockIHandler_Expecter) GetByUser(ctx interface{}) *MockIHandler_GetByUser_Call {
	return &MockIHandler_GetByUser_Call{Call: _e.mock.On("GetByUser", ctx)}
}

func (_c *MockIHandler_GetByUser_Call) Run(run func(ctx *gin.Context)) *MockIHandler_GetByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gin.Context
		if args[0] != nil {
			arg0 = args[0].(*gin.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIHandler_GetByUser_Call) Return() *MockIHandler_GetByUser_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockIHandler_GetByUser_Call) RunAndReturn(run func(ctx *gin.Context)) *MockIHandler_GetByUser_Call {
	_c.Run(run)
	return _c
}

// NewMockIRepository creates a new instance of MockIRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIRepository {
	mock := &MockIRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIRepository is an autogenerated mock type for the IRepository type
type MockIRepository struct {
	mock.Mock
}

type MockIRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIRepository) EXPECT() *MockIRepository_Expecter {
	return &MockIRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockIRepository
func (_mock *MockIRepository) Create(favorite *model.Favorite) error {
	ret := _mock.Called(favorite)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*model.Favorite) error); ok {
		r0 = returnFunc(favorite)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockIRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - favorite *model.Favorite
func (_e *MockIRepository_Expecter) Create(favorite interface{}) *MockIRepository_Create_Call {
	return &MockIRepository_Create_Call{Call: _e.mock.On("Create", favorite)}
}

func (_c *MockIRepository_Create_Call) Run(run func(favorite *model.Favorite)) *MockIRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *model.Favorite
		if args[0] != nil {
			arg0 = args[0].(*model.Favorite)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIRepository_Create_Call) Return(err error) *MockIRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIRepository_Create_Call) RunAndReturn(run func(favorite *model.Favorite) error) *MockIRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockIRepository
func (_mock *MockIRepository) Get(userID string) (model.Favorites, error) {
	ret := _mock.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 model.Favorites
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (model.Favorites, error)); ok {
		return returnFunc(userID)
	}
	if returnFunc, ok := ret.Get(0).(func(string) model.Favorites); ok {
		r0 = returnFunc(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(model.Favorites)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockIRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - userID string
func (_e *MockIRepository_Expecter) Get(userID interface{}) *MockIRepository_Get_Call {
	return &MockIRepository_Get_Call{Call: _e.mock.On("Get", userID)}
}

func (_c *MockIRepository_Get_Call) Run(run func(userID string)) *MockIRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIRepository_Get_Call) Return(favorites model.Favorites, err error) *MockIRepository_Get_Call {
	_c.Call.Return(favorites, err)
	return _c
}

func (_c *MockIRepository_Get_Call) RunAndReturn(run func(userID string) (model.Favorites, error)) *MockIRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUser provides a mock function for the type MockIRepository
func (_mock *MockIRepository) GetByUser(userID string) (model.FoodRecipes, error) {
	ret := _mock.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for GetByUser")
	}

	var r0 model.FoodRecipes
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (model.FoodRecipes, error)); ok {
		return returnFunc(userID)
	}
	if returnFunc, ok := ret.Get(0).(func(string) model.FoodRecipes); ok {
		r0 = returnFunc(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(model.FoodRecipes)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIRepository_GetByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUser'
type MockIRepository_GetByUser_Call struct {
	*mock.Call
}

// GetByUser is a helper method to define mock.On call
//   - userID string
func (_e *MockIRepository_Expecter) GetByUser(userID interface{}) *MockIRepository_GetByUser_Call {
	return &MockIRepository_GetByUser_Call{Call: _e.mock.On("GetByUser", userID)}
}

func (_c *MockIRepository_GetByUser_Call) Run(run func(userID string)) *MockIRepository_GetByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIRepository_GetByUser_Call) Return(foodRecipes model.FoodRecipes, err error) *MockIRepository_GetByUser_Call {
	_c.Call.Return(foodRecipes, err)
	return _c
}

func (_c *MockIRepository_GetByUser_Call) RunAndReturn(run func(userID string) (model.FoodRecipes, error)) *MockIRepository_GetByUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIUserService creates a new instance of MockIUserService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIUserService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIUserService {
	mock := &MockIUserService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIUserService is an autogenerated mock type for the IUserService type
type MockIUserService struct {
	mock.Mock
}

type MockIUserService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIUserService) EXPECT() *MockIUserService_Expecter {
	return &MockIUserService_Expecter{mock: &_m.Mock}
}

// GetByID provides a mock function for the type MockIUserService
func (_mock *MockIUserService) GetByID(claims model.Claims) (model.User, error) {
	ret := _mock.Called(claims)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 model.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(model.Claims) (model.User, error)); ok {
		return returnFunc(claims)
	}
	if returnFunc, ok := ret.Get(0).(func(model.Claims) model.User); ok {
		r0 = returnFunc(claims)
	} else {
		r0 = ret.Get(0).(model.User)
	}
	if returnFunc, ok := ret.Get(1).(func(model.Claims) error); ok {
		r1 = returnFunc(claims)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIUserService_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockIUserService_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - claims model.Claims
func (_e *MockIUserService_Expecter) GetByID(claims interface{}) *MockIUserService_GetByID_Call {
	return &MockIUserService_GetByID_Call{Call: _e.mock.On("GetByID", claims)}
}

func (_c *MockIUserService_GetByID_Call) Run(run func(claims model.Claims)) *MockIUserService_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 model.Claims
		if args[0] != nil {
			arg0 = args[0].(model.Claims)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIUserService_GetByID_Call) Return(user model.User, err error) *MockIUserService_GetByID_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockIUserService_GetByID_Call) RunAndReturn(run func(claims model.Claims) (model.User, error)) *MockIUserService_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetRecipes provides a mock function for the type MockIUserService
func (_mock *MockIUserService) GetRecipes(userID string, claims model.Claims) (model.FoodRecipes, error) {
	ret := _mock.Called(userID, claims)

	if len(ret) == 0 {
		panic("no return value specified for GetRecipes")
	}

	var r0 model.FoodRecipes
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, model.Claims) (model.FoodRecipes, error)); ok {
		return returnFunc(userID, claims)
	}
	if returnFunc, ok := ret.Get(0).(func(string, model.Claims) model.FoodRecipes); ok {
		r0 = returnFunc(userID, claims)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(model.FoodRecipes)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, model.Claims) error); ok {
		r1 = returnFunc(userID, claims)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIUserService_GetRecipes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRecipes'
type MockIUserService_GetRecipes_Call struct {
	*mock.Call
}

// GetRecipes is a helper method to define mock.On call
//   - userID string
//   - claims model.Claims
func (_e *MockIUserService_Expecter) GetRecipes(userID interface{}, claims interface{}) *MockIUserService_GetRecipes_Call {
	return &MockIUserService_GetRecipes_Call{Call: _e.mock.On("GetRecipes", userID, claims)}
}

func (_c *MockIUserService_GetRecipes_Call) Run(run func(userID string, claims model.Claims)) *MockIUserService_GetRecipes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 model.Claims
		if args[1] != nil {
			arg1 = args[1].(model.Claims)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIUserService_GetRecipes_Call) Return(foodRecipes model.FoodRecipes, err error) *MockIUserService_GetRecipes_Call {
	_c.Call.Return(foodRecipes, err)
	return _c
}

func (_c *MockIUserService_GetRecipes_Call) RunAndReturn(run func(userID string, claims model.Claims) (model.FoodRecipes, error)) *MockIUserService_GetRecipes_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertWithClaims provides a mock function for the type MockIUserService
func (_mock *MockIUserService) UpsertWithClaims(claims model.Claims) (model.User, error) {
	ret := _mock.Called(claims)

	if len(ret) == 0 {
		panic("no return value specified for UpsertWithClaims")
	}

	var r0 model.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(model.Claims) (model.User, error)); ok {
		return returnFunc(claims)
	}
	if returnFunc, ok := ret.Get(0).(func(model.Claims) model.User); ok {
		r0 = returnFunc(claims)
	} else {
		r0 = ret.Get(0).(model.User)
	}
	if returnFunc, ok := ret.Get(1).(func(model.Claims) error); ok {
		r1 = returnFunc(claims)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIUserService_UpsertWithClaims_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertWithClaims'
type MockIUserService_UpsertWithClaims_Call struct {
	*mock.Call
}

// UpsertWithClaims is a helper method to define mock.On call
//   - claims model.Claims
func (_e *MockIUserService_Expecter) UpsertWithClaims(claims interface{}) *MockIUserService_UpsertWithClaims_Call {
	return &MockIUserService_UpsertWithClaims_Call{Call: _e.mock.On("UpsertWithClaims", claims)}
}

func (_c *MockIUserService_UpsertWithClaims_Call) Run(run func(claims model.Claims)) *MockIUserService_UpsertWithClaims_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 model.Claims
		if args[0] != nil {
			arg0 = args[0].(model.Claims)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIUserService_UpsertWithClaims_Call) Return(user model.User, err error) *MockIUserService_UpsertWithClaims_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockIUserService_UpsertWithClaims_Call) RunAndReturn(run func(claims model.Claims) (model.User, error)) *MockIUserService_UpsertWithClaims_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIService creates a new instance of MockIService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIService {
	mock := &MockIService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIService is an autogenerated mock type for the IService type
type MockIService struct {
	mock.Mock
}

type MockIService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIService) EXPECT() *MockIService_Expecter {
	return &MockIService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockIService
func (_mock *MockIService) Create(request dto.FavoriteRequest, claims model.Claims) (model.Favorite, error) {
	ret := _mock.Called(request, claims)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 model.Favorite
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(dto.FavoriteRequest, model.Claims) (model.Favorite, error)); ok {
		return returnFunc(request, claims)
	}
	if returnFunc, ok := ret.Get(0).(func(dto.FavoriteRequest, model.Claims) model.Favorite); ok {
		r0 = returnFunc(request, claims)
	} else {
		r0 = ret.Get(0).(model.Favorite)
	}
	if returnFunc, ok := ret.Get(1).(func(dto.FavoriteRequest, model.Claims) error); ok {
		r1 = returnFunc(request, claims)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockIService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - request dto.FavoriteRequest
//   - claims model.Claims
func (_e *MockIService_Expecter) Create(request interface{}, claims interface{}) *MockIService_Create_Call {
	return &MockIService_Create_Call{Call: _e.mock.On("Create", request, claims)}
}

func (_c *MockIService_Create_Call) Run(run func(request dto.FavoriteRequest, claims model.Claims)) *MockIService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 dto.FavoriteRequest
		if args[0] != nil {
			arg0 = args[0].(dto.FavoriteRequest)
		}
		var arg1 model.Claims
		if args[1] != nil {
			arg1 = args[1].(model.Claims)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIService_Create_Call) Return(favorite model.Favorite, err error) *MockIService_Create_Call {
	_c.Call.Return(favorite, err)
	return _c
}

func (_c *MockIService_Create_Call) RunAndReturn(run func(request dto.FavoriteRequest, claims model.Claims) (model.Favorite, error)) *MockIService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockIService
func (_mock *MockIService) Get(userID string) (model.Favorites, error) {
	ret := _mock.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 model.Favorites
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (model.Favorites, error)); ok {
		return returnFunc(userID)
	}
	if returnFunc, ok := ret.Get(0).(func(string) model.Favorites); ok {
		r0 = returnFunc(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(model.Favorites)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIService_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockIService_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - userID string
func (_e *MockIService_Expecter) Get(userID interface{}) *MockIService_Get_Call {
	return &MockIService_Get_Call{Call: _e.mock.On("Get", userID)}
}

func (_c *MockIService_Get_Call) Run(run func(userID string)) *MockIService_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIService_Get_Call) Return(favorites model.Favorites, err error) *MockIService_Get_Call {
	_c.Call.Return(favorites, err)
	return _c
}

func (_c *MockIService_Get_Call) RunAndReturn(run func(userID string) (model.Favorites, error)) *MockIService_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUser provides a mock function for the type MockIService
func (_mock *MockIService) GetByUser(claims model.Claims) (model.FoodRecipes, error) {
	ret := _mock.Called(claims)

	if len(ret) == 0 {
		panic("no return value specified for GetByUser")
	}

	var r0 model.FoodRecipes
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(model.Claims) (model.FoodRecipes, error)); ok {
		return returnFunc(claims)
	}
	if returnFunc, ok := ret.Get(0).(func(model.Claims) model.FoodRecipes); ok {
		r0 = returnFunc(claims)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(model.FoodRecipes)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(model.Claims) error); ok {
		r1 = returnFunc(claims)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIService_GetByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUser'
type MockIService_GetByUser_Call struct {
	*mock.Call
}

// GetByUser is a helper method to define mock.On call
//   - claims model.Claims
func (_e *MockIService_Expecter) GetByUser(claims interface{}) *MockIService_GetByUser_Call {
	return &MockIService_GetByUser_Call{Call: _e.mock.On("GetByUser", claims)}
}

func (_c *MockIService_GetByUser_Call) Run(run func(claims model.Claims)) *MockIService_GetByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 model.Claims
		if args[0] != nil {
			arg0 = args[0].(model.Claims)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIService_GetByUser_Call) Return(foodRecipes model.FoodRecipes, err error) *MockIService_GetByUser_Call {
	_c.Call.Return(foodRecipes, err)
	return _c
}

func (_c *MockIService_GetByUser_Call) RunAndReturn(run func(claims model.Claims) (model.FoodRecipes, error)) *MockIService_GetByUser_Call {
	_c.Call.Return(run)
	return _c
}
