import type { Metadata } from 'next'
import { Prompt } from 'next/font/google'
import './globals.css'

import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'
import Provider from '@/lib/provider'

export const metadata: Metadata = {
  title: 'Wongnok App',
  description: 'Generated by create next app',
}

const prompt = Prompt({
  subsets: ['thai'],
  weight: ['400', '700'],
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en' className={prompt.className}>
      <body suppressHydrationWarning={true}>
        <main className='flex flex-col min-h-screen mx-30'>
          <Provider>
            <Navbar />
            <div className='flex-1 flex flex-col'>{children}</div>
            <Footer />
          </Provider>
        </main>
      </body>      
    </html>
  )
}
